from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'start'
        self.MirrorCommand = f'mr{CMD_INDEX}'
        self.UnzipMirrorCommand = f'unzipmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'zipmirror{CMD_INDEX}'
        self.CancelMirror = f'cancel{CMD_INDEX}'
        self.CancelAllCommand = f'cancelall{CMD_INDEX}'
        self.ListCommand = f'list'
        self.SearchCommand = f'search{CMD_INDEX}'
        self.StatusCommand = f's'
        self.AuthorizedUsersCommand = f'users{CMD_INDEX}'
        self.AuthorizeCommand = f'authorize'
        self.UnAuthorizeCommand = f'unauthorize'
        self.AddSudoCommand = f'addsudo'
        self.RmSudoCommand = f'rmsudo'
        self.PingCommand = f'ping'
        self.RestartCommand = f'rs{CMD_INDEX}'
        self.StatsCommand = f'stats'
        self.HelpCommand = f'help{CMD_INDEX}'
        self.LogCommand = f'log{CMD_INDEX}'
        self.CloneCommand = f'c{CMD_INDEX}'
        self.CountCommand = f'count{CMD_INDEX}'
        self.WatchCommand = f'watch{CMD_INDEX}'
        self.ZipWatchCommand = f'zipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'qbmr{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'qbunzipmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'qbzipmirror{CMD_INDEX}'
        self.DeleteCommand = f'del{CMD_INDEX}'
        self.ShellCommand = f'shell{CMD_INDEX}'
        self.ExecHelpCommand = f'exechelp{CMD_INDEX}'
        self.LeechSetCommand = f'ls{CMD_INDEX}'
        self.SetThumbCommand = f'set{CMD_INDEX}'
        self.LeechCommand = f'l{CMD_INDEX}'
        self.UnzipLeechCommand = f'uzl{CMD_INDEX}'
        self.ZipLeechCommand = f'zipleech{CMD_INDEX}'
        self.QbLeechCommand = f'qbl{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'qbuzl{CMD_INDEX}'
        self.QbZipLeechCommand = f'qbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'leechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'leechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'rsslist{CMD_INDEX}'
        self.RssGetCommand = f'rssget{CMD_INDEX}'
        self.RssSubCommand = f'rsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'rssunsub{CMD_INDEX}'
        self.RssSettingsCommand = f'rssset{CMD_INDEX}'
        self.EvalCommand = f'eval{CMD_INDEX}'
        self.ExecCommand = f'exec{CMD_INDEX}'
        self.ClearLocalsCommand = f'clearlocals{CMD_INDEX}'

BotCommands = _BotCommands()
